Don't reuse values on upgrade
Parameter causes error in some cases, for example:

Error: UPGRADE FAILED: template: kubewarden-controller/templates/serviceaccount.yaml:11:17: executing "kubewarden-controller/templates/serviceaccount.yaml" at <.Values.auditScanner.serviceAccountName>: nil pointer evaluating interface {}.serviceAccountName
Signed-off-by: Martin Kravec <kravciak@gmail.com>