Fix prometheus maximumStartupDurationSeconds error
```
Release "prometheus" does not exist. Installing it now.
   Error: 1 error occurred:
   	* Prometheus.monitoring.coreos.com "prometheus-kube-prometheus-prometheus" is invalid: spec.maximumStartupDurationSeconds: Invalid value: 0: spec.maximumStartupDurationSeconds in body should be greater than or equal to 60
```

Signed-off-by: Martin Kravec <kravciak@gmail.com>